name:                derive-cfg
version:             0.1.0.0
github:              "githubuser/derive-cfg"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/derive-cfg#readme>

dependencies:
- base >= 4.7 && < 5

flags:
  debug-step:
    manual: true
    default: false
when:
    condition: flag(debug-step)
    cpp-options: -D DEBUG_STEP
library:
  source-dirs: src
  dependencies:
  - bytestring
  - containers
  - deepseq
  - fgl
  - graphviz
  - hashable
  - intern
  - logict
  - mtl
  - process
  - text
  - transformers
  - unordered-containers

executables:
  derive-cfg:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - containers
    - deepseq
    - derive-cfg
    - hashable
    - intern
    - process
    - syb
    - tiger-haskell




tests:
  derive-cfg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - derive-cfg
